### PR TITLE
Fix broken source links

### LINKED ISSUE #204: The “source” link on the can-define/list/list doc pages doesn’t work
Steps to reproduce:
1. Go to the `can-define/list/list` docs: https://canjs.com/doc/can-define/list/list.html
2. Click the “source” link

Expected results: land on a page like this: https://github.com/canjs/can-define/blob/master/list/docs/define-list.md

Actual results: landed on this page: https://github.com/canjs/canjs/tree/v3.2.2/node_modules/can-define/list/docs/define-list.md

### PR DESCRIPTION
**Pull request by Rlin415**
Retrieve the actual closest package to docObjects that had their
parent's name set to some name higher up in the family tree.

Resolves #204

### CODE REVIEW

File: templates/helpers.js [hunk 1]
```diff
@@ -175,17 +175,16 @@ module.exports = function(docMap, options, getCurrent, helpers, OtherHandlebars)
                 return current;
             }
 
-            var splittedName = current.name.split('/');
-            var hasSlash = splittedName.length > 1;
+            var hasSlash = splitName.length > 1;
```
Comment (Rlin415) [inline templates/helpers.js]: @chasenlehara I think this will cause problems. You defined splitName on line 184, but we are using it here.

Comment (chasenlehara) [inline templates/helpers.js]: Ugh sorry, you’re right, I’ll fix it.
