### PR TITLE
Fix bug preventing loading indicator from showing

### LINKED ISSUE #392: Improve first-load performance
If you load canjs.com with Slow 3G enabled in Chrome’s DevTools, you’ll see it takes ~20 seconds for everything to load. There are probably some easy things we can do to improve the load time.

### PR DESCRIPTION
**Pull request by imaustink**
Fix bug preventing loading indicator from showing

Since we have a CSS animation on the width of the bar, and on a fast network the progress event usaully only fires once (at 100%), hiding the loading indicator eminently after calling `.end()` would not allow the animation to complete before the bar hidden.

This PR adds a timer to wait for the CSS animation before hiding the bar.

closes #392

__Desktop:__
loading-indicator-desktop
__Mobile:__
loading-indicator-mobile
__Slow 3G Mobile:__
loading-indicator-mobile-slow-3g

### CODE REVIEW

**Comment by chasenlehara** [comment]
@imaustink Could you please add a gif for slow connections? I wasn’t seeing the bar _at all_ with a slow 3G connection, as depicted in https://github.com/canjs/bit-docs-html-canjs/issues/391

**Comment by imaustink** [comment]
@chasenlehara oops! My bad! I've added that.

**Comment by imaustink** [comment]
@chasenlehara I made the changes you recommended.

File: static/loading-bar.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
+var starting = 5;
```
Comment (chasenlehara) [inline static/loading-bar.js]: I would move this inline since it’s not reused anywhere.

File: static/loading-bar.js [hunk 2]
```diff
@@ -10,18 +12,27 @@ function LoadingBar(color, parent) {
...
 
-LoadingBar.prototype.start = function(percentage) {
-  percentage = percentage || 0;
-  this.meter.css('width', percentage + '%');
+LoadingBar.prototype.start = function(progress) {
+  if(this.timer){
+    clearTimeout(this.timer);
+    this.timer = null;
+  }
+  this.meter.css('width', progress || starting + '%');
```
Comment (chasenlehara) [inline static/loading-bar.js]: Order of operations here matters. 😊 To make this more clear, I would follow the `progress = progress || 5` pattern.

File: static/loading-bar.js [hunk 3]
```diff
@@ -10,18 +12,27 @@ function LoadingBar(color, parent) {
...
+  this.update(100);
 };
 
-LoadingBar.prototype.update = function(percentage) {
-  this.meter.css('width', percentage + '%');
+LoadingBar.prototype.update = function(progress) {
+  this.meter.css('width', progress + '%');
+  if(progress === 100){
+    this.timer = setTimeout(function(){
+      console.log('hide');
```
Comment (chasenlehara) [inline static/loading-bar.js]: 👋

Comment (imaustink) [reply static/loading-bar.js]: *face palm* I need a linter rule for `console.log` 😝

**Comment by imaustink** [comment]
@chasenlehara good point! I updated the PR.
