### PR TITLE
Fix broken search results in Safari

### LINKED ISSUE #358: Search results are broken in Safari
Most searches result in an error thrown somewhere inside Lunr: `TypeError: undefined is not an object (evaluating 'p._index')`. Some searches, like `canjs` for example, actually work.

This bug is present in desktop and mobile Safari.
image

### PR DESCRIPTION
**Pull request by imaustink**
image

### CODE REVIEW

File: static/search.js [hunk 1]
```diff
@@ -377,7 +377,8 @@ var Search = Control.extend({
 				var split = searchTerm.split(lunr.tokenizer.separator);
 				split.forEach(function(term) {
 					q.term(term, { usePipeline: false, fields: q.allFields, boost: 10 });
-					q.term(term, { usePipeline: false, fields: q.allFields, wildcard: lunr.Query.wildcard.TRAILING });
+					// This line breaks Safari and seems to be useless
+					// q.term(term, { usePipeline: false, fields: q.allFields, wildcard: lunr.Query.wildcard.TRAILING });
```
Comment (chasenlehara) [inline static/search.js]: Remove code that’s not being used anymore 😊

**Comment by imaustink** [comment]
@chasenlehara updated 😄
